version: "3.9"
services:
  backend:
    container_name: go-backend
    build: ./golang
    ports:
      - "8080:8080"
    tty: true


  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://article:gNeqz9FWh0szcHpVz7Umvgf1NUs578uk@dpg-ce9a1hg2i3ms217l9610-a:5432/pgweb?sslmode=disable
    depends_on:
      - dpg-ce9a1hg2i3ms217l9610-a
  dpg-ce9a1hg2i3ms217l9610-a:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: pgweb
      POSTGRES_USER: article
      POSTGRES_PASSWORD: gNeqz9FWh0szcHpVz7Umvgf1NUs578uk
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - pgwebdb-data:/var/lib/postgresql/data
    tty: true
volumes:
  pgwebdb-data:
    name: pg_backend
    driver: local