definitions:
  server.ArticleAllSteps:
    properties:
      author:
        type: string
      likes:
        type: string
      steps:
        items:
          $ref: '#/definitions/server.Step'
        type: array
      title:
        type: string
    type: object
  server.ArticleOneStep:
    properties:
      author:
        type: string
      likes:
        type: string
      step:
        $ref: '#/definitions/server.Step'
      title:
        type: string
    type: object
  server.Code:
    properties:
      code_content:
        type: string
      code_file_name:
        type: string
    type: object
  server.Message:
    properties:
      message:
        type: string
    type: object
  server.Step:
    properties:
      codes:
        items:
          $ref: '#/definitions/server.Code'
        type: array
      content:
        type: string
    type: object
  server.Title:
    properties:
      articleId:
        type: string
      author:
        type: string
      likes:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
  license:
    name: ryuki
  title: article_api
  version: "2.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Message'
      summary: helloを返す
      tags:
      - helloWorld
  /articles:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/server.Title'
            type: array
      summary: 全ての記事のデータを返す
      tags:
      - db
    post:
      parameters:
      - description: Article Json
        in: body
        name: article_json
        required: true
        schema:
          $ref: '#/definitions/server.ArticleAllSteps'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.Message'
      summary: 新しい記事の投稿
      tags:
      - article
  /articles/{article_id}:
    get:
      parameters:
      - description: Article ID
        in: path
        name: article_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.ArticleAllSteps'
      summary: urlパラメータで指定された番号の記事を出力
      tags:
      - article
    put:
      parameters:
      - description: Article ID
        in: path
        name: article_id
        required: true
        type: integer
      - description: Article Json
        in: body
        name: article_json
        required: true
        schema:
          $ref: '#/definitions/server.ArticleAllSteps'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.Message'
      summary: 記事の編集
      tags:
      - article
  /articles/{article_id}/{step_id}:
    get:
      parameters:
      - description: Article ID
        in: path
        name: article_id
        required: true
        type: integer
      - description: Step ID
        in: path
        name: step_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.ArticleOneStep'
      summary: urlパラメータで指定された記事のステップを出力
      tags:
      - article
  /likes/{article_id}:
    put:
      parameters:
      - description: Article ID
        in: path
        name: article_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.Message'
      summary: いいね数の追加
      tags:
      - like
  /swagger:
    get:
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/server.Message'
      summary: /swagger/index.html#/にアクセスするとswaggerを返す
      tags:
      - helloWorld
swagger: "2.0"
